### PR TITLE
Chapter/chatgpt

### PR DESCRIPTION
**Pull request by Aksi0m**
This chapter should shed some light on how and when to use ChatGPT and to not blindly trust its answers. 🤖 🤖

### CODE REVIEW

**Review by antunflas — APPROVED** [review]

**Review by ffloreani — COMMENTED** [review]
I love what you did with the chapter, great idea and kudos for the initiative! 👏 

One idea though - wouldn't it be better to put this chapter in the dev processes handbook? I don't see anything Android related in here, and I believe it would be beneficial to other dev teams as well 😄

**Comment by Aksi0m** [comment]
> One idea though - wouldn't it be better to put this chapter in the dev processes handbook? I don't see anything Android related in here, and I believe it would be beneficial to other dev teams as well 😄

It does def make sense. I'll talk to Gulan if there were any plans on doing that, otherwise we can c/p this there.

**Review by KCeh — APPROVED** [review]
Great chapter 👏 
And kudos for the initiative 🚀 

But I have a few points to discuss:
- As Flo said, this is not Android specific so it makes more sense to move it to dev process handbook.
- That being said, if we are going to merge to Android handbook we also need to remember to modify [chapters.yml](https://github.com/infinum/android-handbook-private/blob/master/chapters.yml), this is more of a note for me so I don't forget
- Why just focus on ChatGPT? It might be the most popular AI tool now, but I think that for software engineers Copilot, CodeWhisperer or some in-house trained model based on open source model might become more useful. So why not just rename this chapter to AI assistance? And add a sentence or two about other options.

**Comment by Aksi0m** [comment]
> Great chapter 👏 And kudos for the initiative 🚀
> 
> But I have a few points to discuss:
> 
> * As Flo said, this is not Android specific so it makes more sense to move it to dev process handbook.
> * That being said, if we are going to merge to Android handbook we also need to remember to modify [chapters.yml](https://github.com/infinum/android-handbook-private/blob/master/chapters.yml), this is more of a note for me so I don't forget
> * Why just focus on ChatGPT? It might be the most popular AI tool now, but I think that for software engineers Copilot, CodeWhisperer or some in-house trained model based on open source model might become more useful. So why not just rename this chapter to AI assistance? And add a sentence or two about other options.

I wanted to concentrate on one AI tool that I have experience with. I leave the how to chapters for other tools to other people who tried them :D 

PR to dev proc handbook is upcoming...

**Comment by KCeh** [comment]
I will close this PR as it merged into dev proc handbook

**Pull request closed without merging**
