### PR TITLE
Updated styles readme with TextView vs Button

### PR DESCRIPTION
**Pull request by mladen1nf**

### CODE REVIEW

**Comment by ffloreani** [comment]
As this is a polarising topic, I'm going to be offering the whole team a chance to share their opinions here (once again).

If you like what Mladen wrote, please leave a 👍. If you don't agree with this, leave a  👎. Also, feel free to write out your feelings on this topic in the comments below.

**Comment by bojankoma** [comment]
👍

**Comment by ffloreani** [comment]
👍

**Comment by mdocevski** [comment]
:+1:

**Comment by mdocevski** [comment]
@ffloreani maybe we should live an emoji on your comment so you don't have to go through comments and count then :smile:

**Comment by ffloreani** [comment]
As no one else wished to state their opinion, I'm merging this. Thanks @mladen1nf for the effort 👍

**Pull request merged**
